In [1]:
import numpy as np

In [2]:
np.repeat(3, 4)

array([3, 3, 3, 3])

In [3]:
x = np.array([[1,2],[3,4]])

In [4]:
x

array([[1, 2],
       [3, 4]])

In [5]:
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [6]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [7]:
np.repeat(x, [1, 2], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])